@extends('layouts.app')
@section('title', 'Hộ dân - ĐẠI PHÚC')

@section('content')
<div x-data="{ showHelp: false }">

  {{-- ==================== HEADER ==================== --}}
  @include('partials.dashboard-header', ['pageTitle' => '🏠 Dashboard Hộ dân'])

  <div class="resident-container">

    {{-- ==================== QR CODE ==================== --}}
    <div class="qr-card" style="margin-bottom:1.5rem">
      <span class="section-badge">📱 Mã QR của bạn</span>
      <h2 style="font-size:1.25rem;font-weight:700;margin-bottom:.25rem">Mã nhận hàng cứu trợ</h2>
      <p style="font-size:.85rem;color:#64748b;margin-bottom:1rem">Đưa mã QR này cho tài xế khi nhận hàng</p>

      <div class="qr-placeholder" id="qrCodeDisplay">
        {{-- QR Code generated by JS --}}
        <div style="text-align:center">
          <div style="width:180px;height:180px;background:#fff;border:2px solid #e2e8f0;border-radius:8px;display:flex;align-items:center;justify-content:center;margin:0 auto">
            <svg viewBox="0 0 100 100" width="160" height="160">
              {{-- Simulated QR pattern --}}
              <rect x="5" y="5" width="25" height="25" fill="#1e293b" rx="2"/>
              <rect x="70" y="5" width="25" height="25" fill="#1e293b" rx="2"/>
              <rect x="5" y="70" width="25" height="25" fill="#1e293b" rx="2"/>
              <rect x="10" y="10" width="15" height="15" fill="#fff" rx="1"/>
              <rect x="75" y="10" width="15" height="15" fill="#fff" rx="1"/>
              <rect x="10" y="75" width="15" height="15" fill="#fff" rx="1"/>
              <rect x="14" y="14" width="7" height="7" fill="#1e293b"/>
              <rect x="79" y="14" width="7" height="7" fill="#1e293b"/>
              <rect x="14" y="79" width="7" height="7" fill="#1e293b"/>
              {{-- Data area --}}
              <rect x="35" y="5" width="5" height="5" fill="#1e293b"/>
              <rect x="45" y="5" width="5" height="5" fill="#1e293b"/>
              <rect x="55" y="5" width="5" height="5" fill="#1e293b"/>
              <rect x="35" y="15" width="5" height="5" fill="#1e293b"/>
              <rect x="50" y="15" width="5" height="5" fill="#1e293b"/>
              <rect x="60" y="15" width="5" height="5" fill="#1e293b"/>
              <rect x="40" y="25" width="5" height="5" fill="#1e293b"/>
              <rect x="55" y="25" width="5" height="5" fill="#1e293b"/>
              <rect x="5" y="35" width="5" height="5" fill="#1e293b"/>
              <rect x="15" y="35" width="5" height="5" fill="#1e293b"/>
              <rect x="25" y="40" width="5" height="5" fill="#1e293b"/>
              <rect x="35" y="35" width="5" height="5" fill="#1e293b"/>
              <rect x="45" y="40" width="5" height="5" fill="#1e293b"/>
              <rect x="55" y="35" width="5" height="5" fill="#1e293b"/>
              <rect x="65" y="40" width="5" height="5" fill="#1e293b"/>
              <rect x="80" y="35" width="5" height="5" fill="#1e293b"/>
              <rect x="90" y="40" width="5" height="5" fill="#1e293b"/>
              <rect x="5" y="50" width="5" height="5" fill="#1e293b"/>
              <rect x="20" y="50" width="5" height="5" fill="#1e293b"/>
              <rect x="35" y="50" width="5" height="5" fill="#1e293b"/>
              <rect x="50" y="50" width="5" height="5" fill="#1e293b"/>
              <rect x="65" y="50" width="5" height="5" fill="#1e293b"/>
              <rect x="80" y="50" width="5" height="5" fill="#1e293b"/>
              <rect x="45" y="60" width="5" height="5" fill="#1e293b"/>
              <rect x="60" y="60" width="5" height="5" fill="#1e293b"/>
              <rect x="70" y="65" width="5" height="5" fill="#1e293b"/>
              <rect x="85" y="60" width="5" height="5" fill="#1e293b"/>
              <rect x="35" y="70" width="5" height="5" fill="#1e293b"/>
              <rect x="50" y="70" width="5" height="5" fill="#1e293b"/>
              <rect x="65" y="75" width="5" height="5" fill="#1e293b"/>
              <rect x="80" y="70" width="5" height="5" fill="#1e293b"/>
              <rect x="90" y="75" width="5" height="5" fill="#1e293b"/>
              <rect x="35" y="85" width="5" height="5" fill="#1e293b"/>
              <rect x="50" y="85" width="5" height="5" fill="#1e293b"/>
              <rect x="70" y="80" width="5" height="5" fill="#1e293b"/>
              <rect x="85" y="85" width="5" height="5" fill="#1e293b"/>
              <rect x="90" y="90" width="5" height="5" fill="#1e293b"/>
            </svg>
          </div>
        </div>
      </div>

      <p style="font-size:.8rem;color:#64748b;margin-top:.75rem">Mã hộ dân: <strong style="color:#0d9488">HD-2026-0891</strong></p>
      <p style="font-size:.8rem;color:#64748b">CCCD: 0123****8901</p>
    </div>

    {{-- ==================== THÔNG TIN ĐƠN HÀNG ==================== --}}
    <div class="qr-card" style="text-align:left;margin-bottom:1.5rem">
      <h3 style="font-size:1.1rem;font-weight:700;margin-bottom:1rem">📋 Thông tin đơn hàng</h3>
      <div style="display:grid;grid-template-columns:1fr 1fr;gap:.75rem">
        <div style="background:#f8fafc;padding:.75rem;border-radius:8px">
          <div style="font-size:.75rem;color:#64748b">Mã đơn</div>
          <div style="font-weight:700;color:#0d9488">DH-2026-0456</div>
        </div>
        <div style="background:#f8fafc;padding:.75rem;border-radius:8px">
          <div style="font-size:.75rem;color:#64748b">Ngày đăng ký</div>
          <div style="font-weight:600">18/03/2026</div>
        </div>
        <div style="background:#f8fafc;padding:.75rem;border-radius:8px">
          <div style="font-size:.75rem;color:#64748b">Khu vực</div>
          <div style="font-weight:600">Xã Hòa Bình, Đà Nẵng</div>
        </div>
        <div style="background:#f8fafc;padding:.75rem;border-radius:8px">
          <div style="font-size:.75rem;color:#64748b">Số người</div>
          <div style="font-weight:600">5 người / hộ</div>
        </div>
      </div>
    </div>

    {{-- ==================== TIMELINE ==================== --}}
    <div class="qr-card" style="text-align:left;margin-bottom:1.5rem">
      <h3 style="font-size:1.1rem;font-weight:700;margin-bottom:.5rem">📍 Theo dõi tiến trình</h3>
      <p style="font-size:.85rem;color:#64748b;margin-bottom:1rem">Cập nhật trạng thái đơn hàng cứu trợ</p>

      <div class="timeline">
        {{-- Step 1 - Done --}}
        <div class="timeline-step done">
          <div class="step-title">✅ Đã đăng ký</div>
          <div class="step-desc">Yêu cầu đã gửi thành công lúc 08:30 ngày 18/03/2026</div>
        </div>

        {{-- Step 2 - Done --}}
        <div class="timeline-step done">
          <div class="step-title">✅ Admin phê duyệt</div>
          <div class="step-desc">Đã được duyệt bởi Admin Trần Văn K lúc 09:15 ngày 18/03/2026</div>
        </div>

        {{-- Step 3 - Active --}}
        <div class="timeline-step active">
          <div class="step-title">🚛 Đang vận chuyển</div>
          <div class="step-desc">Xe TX-089 đang trên đường giao hàng — Dự kiến 14:00 hôm nay</div>
        </div>

        {{-- Step 4 - Pending --}}
        <div class="timeline-step">
          <div class="step-title">📦 Đã nhận hàng</div>
          <div class="step-desc">Chờ xác nhận từ hộ dân khi nhận hàng</div>
        </div>
      </div>
    </div>

    {{-- ==================== LIÊN HỆ ==================== --}}
    <div class="qr-card" style="text-align:left;margin-bottom:1.5rem">
      <h3 style="font-size:1.1rem;font-weight:700;margin-bottom:1rem">📞 Cần hỗ trợ?</h3>
      <div style="display:flex;gap:.75rem;flex-wrap:wrap">
        <a href="tel:1900636838" class="btn btn-orange btn-sm" style="flex:1;justify-content:center;min-width:160px">📞 Hotline: 1900.636.838</a>
        <button class="btn btn-outline-teal btn-sm" @click="showHelp = true" style="flex:1;justify-content:center;min-width:160px">💬 Gửi phản hồi</button>
      </div>
    </div>

    {{-- ==================== NÚT QUAY LẠI ==================== --}}
    <div style="text-align:center;margin-bottom:2rem">
      <a href="/" class="btn btn-outline btn-sm">← Về trang chủ</a>
    </div>

  </div>

  {{-- MODAL: PHẢN HỒI --}}
  <template x-if="showHelp">
    <div class="modal-overlay" @click.self="showHelp = false">
      <div class="modal-box" @click.stop>
        <div class="modal-header">
          <h3>💬 Gửi phản hồi</h3>
          <button class="modal-close" @click="showHelp = false">✕</button>
        </div>
        <div class="modal-body">
          <form onsubmit="handleFeedback(event)">
            <div class="form-group">
              <label class="form-label">Nội dung</label>
              <textarea class="form-control" rows="4" placeholder="Mô tả vấn đề hoặc phản hồi..." required></textarea>
            </div>
            <div class="form-group">
              <label class="form-label">Ảnh đính kèm</label>
              <label class="file-upload">
                <input type="file" accept="image/*" multiple style="display:none" onchange="handleFileUpload(this,'residentPhotoPreview')">
                📎 Chọn ảnh
              </label>
              <div id="residentPhotoPreview" style="display:flex;flex-wrap:wrap;gap:.25rem;margin-top:.5rem"></div>
            </div>
            <button type="submit" class="btn btn-teal btn-lg" style="width:100%">📨 Gửi phản hồi</button>
          </form>
        </div>
      </div>
    </div>
  </template>

</div>
@endsection
